# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MaxTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=125, null=True)),
                ('jan', models.CharField(blank=True, max_length=125, null=True)),
                ('feb', models.CharField(blank=True, max_length=125, null=True)),
                ('mar', models.CharField(blank=True, max_length=125, null=True)),
                ('apr', models.CharField(blank=True, max_length=125, null=True)),
                ('may', models.CharField(blank=True, max_length=125, null=True)),
                ('jun', models.CharField(blank=True, max_length=125, null=True)),
                ('jul', models.CharField(blank=True, max_length=125, null=True)),
                ('aug', models.CharField(blank=True, max_length=125, null=True)),
                ('sep', models.CharField(blank=True, max_length=125, null=True)),
                ('octo', models.CharField(blank=True, max_length=125, null=True)),
                ('nov', models.CharField(blank=True, max_length=125, null=True)),
                ('dec', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_countries', to='climate.Country')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MeanTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=125, null=True)),
                ('jan', models.CharField(blank=True, max_length=125, null=True)),
                ('feb', models.CharField(blank=True, max_length=125, null=True)),
                ('mar', models.CharField(blank=True, max_length=125, null=True)),
                ('apr', models.CharField(blank=True, max_length=125, null=True)),
                ('may', models.CharField(blank=True, max_length=125, null=True)),
                ('jun', models.CharField(blank=True, max_length=125, null=True)),
                ('jul', models.CharField(blank=True, max_length=125, null=True)),
                ('aug', models.CharField(blank=True, max_length=125, null=True)),
                ('sep', models.CharField(blank=True, max_length=125, null=True)),
                ('octo', models.CharField(blank=True, max_length=125, null=True)),
                ('nov', models.CharField(blank=True, max_length=125, null=True)),
                ('dec', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mean_countries', to='climate.Country')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MinTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=125, null=True)),
                ('jan', models.CharField(blank=True, max_length=125, null=True)),
                ('feb', models.CharField(blank=True, max_length=125, null=True)),
                ('mar', models.CharField(blank=True, max_length=125, null=True)),
                ('apr', models.CharField(blank=True, max_length=125, null=True)),
                ('may', models.CharField(blank=True, max_length=125, null=True)),
                ('jun', models.CharField(blank=True, max_length=125, null=True)),
                ('jul', models.CharField(blank=True, max_length=125, null=True)),
                ('aug', models.CharField(blank=True, max_length=125, null=True)),
                ('sep', models.CharField(blank=True, max_length=125, null=True)),
                ('octo', models.CharField(blank=True, max_length=125, null=True)),
                ('nov', models.CharField(blank=True, max_length=125, null=True)),
                ('dec', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_countries', to='climate.Country')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=125, null=True)),
                ('jan', models.CharField(blank=True, max_length=125, null=True)),
                ('feb', models.CharField(blank=True, max_length=125, null=True)),
                ('mar', models.CharField(blank=True, max_length=125, null=True)),
                ('apr', models.CharField(blank=True, max_length=125, null=True)),
                ('may', models.CharField(blank=True, max_length=125, null=True)),
                ('jun', models.CharField(blank=True, max_length=125, null=True)),
                ('jul', models.CharField(blank=True, max_length=125, null=True)),
                ('aug', models.CharField(blank=True, max_length=125, null=True)),
                ('sep', models.CharField(blank=True, max_length=125, null=True)),
                ('octo', models.CharField(blank=True, max_length=125, null=True)),
                ('nov', models.CharField(blank=True, max_length=125, null=True)),
                ('dec', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_countries', to='climate.Country')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Sunshine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=125, null=True)),
                ('jan', models.CharField(blank=True, max_length=125, null=True)),
                ('feb', models.CharField(blank=True, max_length=125, null=True)),
                ('mar', models.CharField(blank=True, max_length=125, null=True)),
                ('apr', models.CharField(blank=True, max_length=125, null=True)),
                ('may', models.CharField(blank=True, max_length=125, null=True)),
                ('jun', models.CharField(blank=True, max_length=125, null=True)),
                ('jul', models.CharField(blank=True, max_length=125, null=True)),
                ('aug', models.CharField(blank=True, max_length=125, null=True)),
                ('sep', models.CharField(blank=True, max_length=125, null=True)),
                ('octo', models.CharField(blank=True, max_length=125, null=True)),
                ('nov', models.CharField(blank=True, max_length=125, null=True)),
                ('dec', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunshine_countries', to='climate.Country')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
